#!/usr/bin/env python3
"""Bring every register and every page in line with CONDITIONS, in one command.

A condition is added, renamed or removed by editing CONDITIONS in build-demo.py. Everything else
follows from that list, but through six registers that are fetched or generated by separate tools,
and a page that reads a register built for yesterday's list describes conditions the reader cannot
see. This runs the tools in the order their inputs require, says what each one changed, builds the
site, audits it, and ends with the list of what still needs a person.

    python3 tools/update-conditions.py               the fast steps: classification, ICD, prevalence,
                                                     vocabulary, site build, audit (a few minutes, network)
    python3 tools/update-conditions.py --bibliography  also rebuild the bibliography from PubMed, the
                                                     registries it rests on, and the research teams
                                                     (15 to 20 minutes more)
    python3 tools/update-conditions.py --dry-run      print the plan and the current gaps, change nothing
    python3 tools/update-conditions.py --only icd,vocab,build   run named steps

Order and why: the classification first, because the ICD codes of the forms documented inside a
card, the vocabulary and the search words all read it; ICD and prevalence next, one Orphanet call per
card; the vocabulary from the classification; then, if asked, the bibliography (which reads the
prevalence file for Orphanet's citations and the vocabulary to tag papers), the registries each paper
rests on, and the research teams (which read the bibliography); then the site; then the audit.

What no code can do, and the audit lists at the end: place a new card in the Oberg-Manske-Tonkin
classification (tools/condition-omt.json, a hand surgeon's judgement); read a code's registry list on
Orphanet, whose pages are rendered in the browser and have no API (tools/orphanet-registries.json);
source a birth prevalence for the map (DOT_RATES in build-demo.py, one verified paper per figure);
and rewrite the sentences on the pages that name a condition in prose.
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import conditions as C  # noqa: E402

STEPS = [
    # key, what it does, command, register it writes, key of the register's per-condition map
    ("hierarchy", "Orphanet classification: term, level, parents, children, ICD codes of every card and of the forms inside it",
     ["build-orphanet-hierarchy.py"], "orphanet-hierarchy.json", "nodes"),
    ("icd", "ICD-10 and ICD-11 mapped by Orphanet for each card, with the hand-curated additions",
     ["build-condition-icd.py"], "condition-icd.json", "conditions"),
    ("prevalence", "Orphanet's birth prevalence rows for each card, with the studies they cite resolved on PubMed",
     ["build-condition-prevalence.py"], "condition-prevalence.json", "conditions"),
    ("vocab", "the patterns the bibliography matches a paper against, from Orphanet's terms and synonyms",
     ["build-condition-vocab.py"], "condition-vocab.json", None),
    ("bibliography", "the bibliography from PubMed, Crossref and the member and registry websites (long), then the registries each paper rests on",
     ["build-bibliography.py"], "bibliography.json", None),
    ("researchers", "the research teams, from the bibliography's author affiliations",
     ["build-researchers.py"], "researchers.json", None),
    ("build", "the site itself: every page, the search index, llms.txt, the data files",
     None, None, None),
    ("audit", "the checks: every page agrees with the list, and what is left for a person",
     ["audit-conditions.py"], None, None),
]
FAST = ["hierarchy", "icd", "prevalence", "vocab", "build", "audit"]
LONG = ["bibliography", "researchers"]


def keys_of(register, key):
    """What a register holds, as a set that can be compared before and after a step: the keys of a
    per-condition map, or an identifier for each record of a list (a paper's PMID or DOI, a team's
    institution), so that the report can say what was gained and what was lost."""
    d = C.load(register)
    if not d:
        return set()
    v = d.get(key) if key else next((d[k] for k in ("entries", "teams", "rules") if k in d), d)
    if isinstance(v, dict):
        return set(v)
    ident = lambda r: str(r.get("pmid") or r.get("doi") or r.get("institution") or r.get("pattern") or r.get("title") or r)
    return {ident(r) if isinstance(r, dict) else str(r) for r in (v or [])}


def vocab_codes():
    """Every code a bibliography rule names: the hand-written VOCAB in build-bibliography.py and the generated file."""
    src = (HERE / "build-bibliography.py").read_text(encoding="utf-8")
    blk = src[src.index("VOCAB = [  #"):]
    blk = blk[:blk.index("\n]\n")]
    manual = set(re.findall(r'"(\d+)"\)', blk))
    return manual | {r["code"] for r in (C.load("condition-vocab.json") or {}).get("rules", [])}


def gaps():
    """What each register is missing for the current list, before anything runs."""
    cards = C.conditions()
    names = {c["name"] for c in cards}
    coded = {c["code"]: c["name"] for c in cards if c["code"]}
    hier = C.hierarchy()
    out = {
        "hierarchy": sorted(coded[c] for c in coded if c not in hier.get("nodes", {})),
        "icd": sorted(names - set((C.load("condition-icd.json") or {}).get("conditions", {}))),
        "prevalence": sorted(n for c, n in coded.items() if n not in (C.load("condition-prevalence.json") or {}).get("conditions", {})),
        "vocab": sorted(coded[c] for c in coded if c not in vocab_codes()),
        "omt (by hand)": sorted(names - set((C.load("condition-omt.json") or {}).get("conditions", {}))),
        "registries read on Orphanet (by hand)": sorted(coded[c] for c in coded if c not in set((C.load("orphanet-registries.json") or {}).get("codes_checked", []))),
    }
    stale = {
        "icd": sorted(set((C.load("condition-icd.json") or {}).get("conditions", {})) - names),
        "prevalence": sorted(set((C.load("condition-prevalence.json") or {}).get("conditions", {})) - names),
        "omt": sorted(set((C.load("condition-omt.json") or {}).get("conditions", {})) - names),
    }
    return out, stale


def run_step(key, dry):
    step = next(s for s in STEPS if s[0] == key)
    _k, what, cmd, register, mapkey = step
    print(f"\n── {key}: {what}")
    if dry:
        print(f"   would run: {'python3 build-demo.py' if cmd is None else 'python3 tools/' + cmd[0]}")
        return True
    before = keys_of(register, mapkey) if register else set()
    t0 = time.time()
    argv = [sys.executable, str(ROOT / "build-demo.py")] if cmd is None else [sys.executable, str(HERE / cmd[0])]
    r = subprocess.run(argv, cwd=ROOT, capture_output=True, text=True)
    tail = "\n".join((r.stdout + r.stderr).strip().splitlines()[-4:])
    print("   " + tail.replace("\n", "\n   "))
    if r.returncode != 0 and key != "audit":
        print(f"   FAILED after {time.time() - t0:.0f}s (exit {r.returncode})")
        return False
    if register:
        after = keys_of(register, mapkey)
        added, gone = sorted(after - before), sorted(before - after)
        if added or gone:
            print(f"   {register}: +{len(added)} {added[:6]}{'…' if len(added) > 6 else ''}  -{len(gone)} {gone[:6]}{'…' if len(gone) > 6 else ''}")
        else:
            print(f"   {register}: same {len(after)} entries, contents refreshed")
    print(f"   done in {time.time() - t0:.0f}s")
    return r.returncode == 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--bibliography", action="store_true", help="also rebuild the bibliography and the research teams (long)")
    ap.add_argument("--dry-run", action="store_true", help="print the plan and the gaps, change nothing")
    ap.add_argument("--only", help="comma-separated step keys to run, in pipeline order")
    a = ap.parse_args()
    cards = C.conditions()
    print(f"{len(cards)} cards in CONDITIONS, {len([c for c in cards if c['code']])} with an ORPHAcode")
    g, stale = gaps()
    for k, v in g.items():
        print(f"  {k:40} {'complete' if not v else str(len(v)) + ' missing: ' + ', '.join(v[:5]) + ('…' if len(v) > 5 else '')}")
    for k, v in stale.items():
        if v:
            fate = "kept, this register is written by hand" if k == "omt" else "pruned when the step reruns"
            print(f"  {k:40} {len(v)} row(s) for conditions no longer on the site ({fate}): {', '.join(v[:4])}{'…' if len(v) > 4 else ''}")
    order = [s[0] for s in STEPS]
    if a.only:
        wanted = [k.strip() for k in a.only.split(",")]
        bad = [k for k in wanted if k not in order]
        if bad:
            raise SystemExit(f"unknown step(s): {bad}; choose from {order}")
        plan = [k for k in order if k in wanted]
    else:
        plan = [k for k in order if k in FAST or (a.bibliography and k in LONG)]
    print(f"\nplan: {' → '.join(plan)}" + ("" if a.bibliography or a.only else "   (add --bibliography to rebuild the literature, 15 to 20 min)"))
    ok = True
    for key in plan:
        if not run_step(key, a.dry_run):
            ok = False
            if key != "audit":
                print("\nstopped: fix the step above and rerun")
                break
    if not a.dry_run:
        print("\n" + ("update complete; the audit's notes above are the work left for a person" if ok
                      else "update finished with failures; see FAIL lines above"))
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
